In [13]:
import torch
import numpy as np

In [11]:
variational_parameters = torch.empty(31, 73, requires_grad=True)

In [15]:
torch.flatten(variational_parameters).data

tensor([0.0000e+00, 0.0000e+00, 1.9649e-24,  ..., 1.7226e+11, 1.7988e-19,
        1.7894e-19])

In [47]:
d_logits = torch.nn.Parameter(torch.FloatTensor(8447, 30, ))
torch.nn.init.xavier_uniform_(d_logits, 1)
t_logits = torch.nn.Parameter(torch.FloatTensor(30, 3012, ))
torch.nn.init.xavier_normal_(t_logits, 0.5)

Parameter containing:
tensor([[ 0.0078, -0.0089, -0.0080,  ...,  0.0021, -0.0037,  0.0192],
        [-0.0124, -0.0009,  0.0039,  ..., -0.0019,  0.0230,  0.0007],
        [ 0.0037, -0.0036, -0.0044,  ..., -0.0118,  0.0211,  0.0174],
        ...,
        [-0.0031, -0.0006,  0.0099,  ..., -0.0058,  0.0018, -0.0248],
        [ 0.0076, -0.0120,  0.0019,  ...,  0.0070, -0.0080, -0.0178],
        [ 0.0135,  0.0045, -0.0190,  ..., -0.0103,  0.0046, -0.0210]],
       requires_grad=True)

In [48]:
d_logits.min(), d_logits.max()

(tensor(-0.0266, grad_fn=<MinBackward1>),
 tensor(0.0266, grad_fn=<MaxBackward1>))

In [49]:
t_logits.min(), t_logits.max()

(tensor(-0.0562, grad_fn=<MinBackward1>),
 tensor(0.0521, grad_fn=<MaxBackward1>))

In [53]:
torch.clamp(t_logits, max=1e3, min=-1e3)

tensor([[ 0.0078, -0.0089, -0.0080,  ...,  0.0021, -0.0037,  0.0192],
        [-0.0124, -0.0009,  0.0039,  ..., -0.0019,  0.0230,  0.0007],
        [ 0.0037, -0.0036, -0.0044,  ..., -0.0118,  0.0211,  0.0174],
        ...,
        [-0.0031, -0.0006,  0.0099,  ..., -0.0058,  0.0018, -0.0248],
        [ 0.0076, -0.0120,  0.0019,  ...,  0.0070, -0.0080, -0.0178],
        [ 0.0135,  0.0045, -0.0190,  ..., -0.0103,  0.0046, -0.0210]],
       grad_fn=<ClampBackward>)

In [55]:
torch.any(torch.isnan(torch.clamp(t_logits, max=1e3, min=-1e3)))

tensor(False)

In [56]:
from gensim.test.utils import common_corpus, common_dictionary

In [59]:
common_dictionary.token2id

{'computer': 0,
 'eps': 8,
 'graph': 10,
 'human': 1,
 'interface': 2,
 'minors': 11,
 'response': 3,
 'survey': 4,
 'system': 5,
 'time': 6,
 'trees': 9,
 'user': 7}

In [1]:
def func(a,b,c):
    return print(a,b,c)

In [2]:
func(*(1,2), 3)

1 2 3


In [4]:
(1,)[0]

1

In [7]:
x, = (1,)

In [8]:
x

1

In [43]:
test_t = torch.arange(500, dtype=torch.float32).reshape((5, 100))

In [53]:
test_gather = np.array([[1, 0, 0], 
                            [1, 1, 0]])

In [54]:
gathered = np.take_along_axis(test_t.reshape((1, 5, 100)), test_gather.reshape((2, 1, 3)), axis=-1)
normed = gathered/torch.sum(gathered, dim=1,keepdim=True)

In [62]:
(normed * torch.unsqueeze(torch.tensor(test_gather), 1))

tensor([[[0.0010, 0.0000, 0.0000],
         [0.1005, 0.0000, 0.0000],
         [0.2000, 0.0000, 0.0000],
         [0.2995, 0.0000, 0.0000],
         [0.3990, 0.0000, 0.0000]],

        [[0.0010, 0.0010, 0.0000],
         [0.1005, 0.1005, 0.0000],
         [0.2000, 0.2000, 0.0000],
         [0.2995, 0.2995, 0.0000],
         [0.3990, 0.3990, 0.0000]]])

In [66]:
torch.sum(-0.5*(normed - gathered)**2)

tensor(-901206.8125)

In [70]:
torch.nn.MSELoss(reduction='sum')(normed, gathered)/2

tensor(901206.8125)

In [73]:
test_t.data

tensor([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
          12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,
          24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,
          36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,
          48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,
          60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,
          72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,
          84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,
          96.,  97.,  98.,  99.],
        [100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110., 111.,
         112., 113., 114., 115., 116., 117., 118., 119., 120., 121., 122., 123.,
         124., 125., 126., 127., 128., 129., 130., 131., 132., 133., 134., 135.,
         136., 137., 138., 139., 140., 141., 142., 143., 144., 145., 146., 

In [74]:
np.random.randint(0, 400)

245

In [79]:
torch.nn.BCELoss()(torch.tensor(0.1), torch.tensor(0.5))

tensor(1.2040)

In [80]:
?torch.nn.BCELoss

In [86]:
np.random.randint(0, 100, size=10, replace=)

tensor([[ 94.,   7.,  81.,  16.,  49.,  60.,   0.,  17.,  66.,   5.],
        [194., 107., 181., 116., 149., 160., 100., 117., 166., 105.],
        [294., 207., 281., 216., 249., 260., 200., 217., 266., 205.],
        [394., 307., 381., 316., 349., 360., 300., 317., 366., 305.],
        [494., 407., 481., 416., 449., 460., 400., 417., 466., 405.]])

In [87]:
np.random.choice(np.arange(100), size=10, replace=False)

array([82,  4, 22, 35, 28, 96, 45, 48, 95, 65])